CREATE TABLE UTL$DB_COMPILE_OBJ_IGNORE
(
  ID                               NUMBER(22,0)          NOT NULL,
  SCHEMA_NAME                      VARCHAR2(30 BYTE)     NOT NULL,
  OBJECT_NAME                      VARCHAR2(30 BYTE)     NOT NULL
)
/
CREATE INDEX I_UTL$DB_COMPILE_OBJ_IGNORE
  ON UTL$DB_COMPILE_OBJ_IGNORE(
   SCHEMA_NAME,
   OBJECT_NAME
  )
/
CREATE UNIQUE INDEX UTL$DB_COMPILE_OBJ_IGNORE_PK
  ON UTL$DB_COMPILE_OBJ_IGNORE(ID)
/
ALTER TABLE UTL$DB_COMPILE_OBJ_IGNORE ADD(
  CONSTRAINT UTL$DB_COMPILE_OBJ_IGNORE_PK PRIMARY KEY(ID)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
    USING INDEX UTL$DB_COMPILE_OBJ_IGNORE_PK
    ENABLE VALIDATE
  )
/

CREATE SEQUENCE UTL$DB_COMPILE_OBJ_IGNORE_SEQ
/

CREATE OR REPLACE TRIGGER UTL$DB_COMPILE_OBJ_IGNORE_ID
  BEFORE INSERT ON UTL$DB_COMPILE_OBJ_IGNORE FOR EACH ROW
BEGIN
    IF(:NEW.ID IS NULL) THEN
        SELECT UTL$DB_COMPILE_OBJ_IGNORE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

COMMENT ON TABLE UTL$DB_COMPILE_OBJ_IGNORE IS 'Exclude these objects from the compilation'
/